# Docker image for building Android APKs via buildozer
# Build with:
# docker build --tag=andremiras/etherollapp-android --file=dockerfiles/Dockerfile-android .
# Run with:
# docker run andremiras/etherollapp-android /bin/sh -c 'buildozer android debug'
# Or using the entry point shortcut:
# docker run andremiras/etherollapp-android 'buildozer android debug'
# Or for interactive shell:
# docker run -it --rm andremiras/etherollapp-android
FROM ubuntu:18.04

ENV USER="user"
ENV HOME_DIR="/home/${USER}"
ENV WORK_DIR="${HOME_DIR}" \
    PATH="${HOME_DIR}/.local/bin:${PATH}"
ENV DOCKERFILES_VERSION="develop" \
    DOCKERFILES_URL="https://raw.githubusercontent.com/AndreMiras/dockerfiles"
ENV MAKEFILES_URL="${DOCKERFILES_URL}/${DOCKERFILES_VERSION}/buildozer_android"


# configure locale
RUN apt update -qq > /dev/null && apt install -qq --yes --no-install-recommends \
    locales && \
    locale-gen en_US.UTF-8
ENV LANG="en_US.UTF-8" \
    LANGUAGE="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8"

# install system dependencies (required to setup all the tools)

# install build dependencies (required to successfully build the project)
RUN apt update -qq > /dev/null && apt install -qq --yes --no-install-recommends \
    lsb-release \
    make \
    sudo

# prepare non root env
RUN useradd --create-home --shell /bin/bash ${USER}
# with sudo access and no password
RUN usermod -append --groups sudo ${USER}
RUN echo "%sudo ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER ${USER}
WORKDIR ${WORK_DIR}

COPY Makefile ${WORK_DIR}
RUN sudo make system_dependencies_android

# install buildozer and dependencies
RUN curl --location --progress-bar ${MAKEFILES_URL}/buildozer.mk --output buildozer.mk
RUN make -f buildozer.mk
# enforces buildozer master (d483847) until next release
RUN pip3 install --upgrade https://github.com/kivy/buildozer/archive/d483847.zip

COPY . ${WORK_DIR}
ENTRYPOINT ["./dockerfiles/start.sh"]
