#:import MDTextField kivymd.textfields.MDTextField


<PasswordForm>:
    orientation: 'vertical'
    MDLabel:
        id: account_id
    MDTextField:
        id: password_id
        hint_text: "Password"
        helper_text: "Enter the password to unlock your account"
        helper_text_mode: "on_focus"
        text: root.password
        password: True
        focus: True
        on_text: root.password = args[1]
